engines:
    eslint:
        enabled: false
    duplication:
        enabled: false
        config:
            languages:
                - javascript
exclude_paths:
    - "demo/example.html"
    - "src/async.min.js"
    - "README.md"
    - "package.json"
    - "component.json"
    - "bower.json"
    - "Gruntfile.js"
    - ".tm_properties"
    - ".jshintrc"
    - ".jshintignore"
    - ".gitignore"
    - ".coveralls.yml"
